package:
  name: scikits.odes
  version: "2.3.2"

source:
  git_rev: 73b6548
  git_url: https://github.com/utsekaj42/odes.git

requirements:
  build:
    - python
    - setuptools
    - gcc
    - cython
    - scipy
    - sundials
  run:
    - python
    - cython
    - scipy
    - sundials

test:
  requirements:
    - nose
  imports:
    - scikits.odes

about:
  home: https://github.com/utsekaj42/odes
  license: ""
  license_file: LICENSE.txt
